Use is_file instead of existence in finding .ozy.yaml
Fixes an issue where if you have a magic filesystem on your cwd
(e.g. `envy` via autofs) which dreams up directories if you ask it
...then `ozy` used to:

```
Error: While loading ozy config

Caused by:
    0: Reading config YAML
    1: Is a directory (os error 21)
```